 discord:
  - id: "crawl2"
    discord_channel: "h1_subj"
    discord_username: "notify"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1133356403071926272/ULC5VYa948ESD_ZA_ukD4Kw-2Ljc1VahOnJDdJnEA6lYU87ldsj5F0Xt3_ycGZWDeiCL"

  - id: "crawl2_a"
    discord_channel: "h1_nuclei"
    discord_username: "notify"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1133733126372335646/mF_wQuREZSnhKUUI7n1T0p3mimhLBAQtYzWRusXnXwnd54lc8GKIoJpOGdynen8VuQL6"

  - id: "crawl3"
    discord_channel: "apple_subj"
    discord_username: "notify"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1133761344290697267/htbab7sL_CSejuzhQAz38RNV523ciVVE1R2TzDUg6ji-fxiAbRc14kb1_41EGdTk2A36"

  - id: "crawl3_a"
    discord_channel: "apple_nuclei"
    discord_username: "notify"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1134449999124627496/1oMBVdPHpM_99Fxzg0C0fzzxIJakiigb3k4oywu_vGDE9UUQ5T7nHsRct3rFYxCAqzCo"

  - id: "crawl4"
    discord_channel: "gg_subj"
    discord_username: "notify"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1133765623076364318/1fNUIw7fkxfMLdwrbptWGk08fHDY_eo8thpDCPMnHKHIJKOmtkW6iMcQPOaNoqnGAEco"

  - id: "crawl4_a"
    discord_channel: "gg_nuclei"
    discord_username: "notify"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1134450835598880799/M-t9-L91V9_nj4KZ8jiUZ6ndAGaaJ9jX4ArqkMEqoDEeEg5Kz9dpjfTLqetBVrV1pSQh"

  - id: "crawl5"
    discord_channel: "redbull_subj"
    discord_username: "notify"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1133767257063948340/WjPK3E8EiNNEsYWMisLYGcW-C1GggFueyYwk3jQyqHmD4XHyGE5_DLeKIyS-f1jvncS4"

  - id: "crawl5_a"
    discord_channel: "redbull_nuclei"
    discord_username: "notify"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1134451297093943408/3SDj8AseL7Z2OKEaiL0XE2L9h6ibW-EOtxEzMCpo5PPwmNZmmSAg5YnPP5g_2t2s2uFg"

  - id: "crawl6"
    discord_channel: "fb_subj"
    discord_username: "notify"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1135212327969505400/MsfaXBpzdhpejw1S_2QzpKjJ8UbEbfbtIdEWgmRpIgIpsbKeTinlJV-7A5az204PnjJc"

  - id: "crawl6_a"
    discord_channel: "fb_nuclei"
    discord_username: "notify"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1135212468470304868/y6Nj2AvUgvl1rg65Nn-I2LOxlmH428pLLIchkom3hlNWcoN6urs_yYUEqSKp457c07Ar"

  - id: "crawl7"
    discord_channel: "ms_nuclei"
    discord_username: "notify"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1137068203831459920/PCKptumRmKG-MEO1TQiBx9sHG0HT4j6EyDTMIH5U2uD_gUrlQbCPoDEMmXMEKw2nWnLr"

  - id: "crawl7_a"
    discord_channel: "ms_shodan"
    discord_username: "notify"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1138073760843444304/2ej2EC0lTwGlY_nmKoBe-R2kYdQZco067GbIhU4soMoO36hYIOif2r_CSfGRyKLfn1QZ"

  - id: "crawl8"
    discord_channel: "harvard"
    discord_username: "notify"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1138807429505757265/rsJaxtrv9lc9z487VlGWqO_L07uHeQDAlFMnLHDInSfS_ELIXeSb4K6K9ypLVjI3Qx_4"

